services:
  app:
    container_name: comar_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://comar_db:27017/app
      - JWT_SECRET=your-secret-key
    depends_on:
      - db

  db:
    image: mongo:7.0
    container_name: comar_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/comar_db

volumes:
  mongo-data:
